"""add teams

Revision ID: 5e01bce9e70e
Revises: 51df7e7b4525
Create Date: 2026-02-17 10:06:04.739443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e01bce9e70e'
down_revision = '51df7e7b4525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olympics_team_agg',
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('figure_skating', sa.Integer(), nullable=True),
    sa.Column('curling', sa.Integer(), nullable=True),
    sa.Column('snowboard', sa.Float(), nullable=True),
    sa.Column('hockey', sa.Float(), nullable=True),
    sa.Column('biathlon', sa.Integer(), nullable=True),
    sa.Column('freestyle', sa.Integer(), nullable=True),
    sa.Column('short_track', sa.Integer(), nullable=True),
    sa.Column('ski_alpenism', sa.Integer(), nullable=True),
    sa.Column('speed_skating', sa.Float(), nullable=True),
    sa.Column('bobsleigh', sa.Float(), nullable=True),
    sa.Column('northern_combination', sa.Integer(), nullable=True),
    sa.Column('total_accounts', sa.Integer(), nullable=True),
    sa.Column('bills_paid', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('team'),
    sa.UniqueConstraint('team', name='uq_olympics_row_team')
    )
    op.create_index('ix_olympics_team_agg_team', 'olympics_team_agg', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_olympics_team_agg_team', table_name='olympics_team_agg')
    op.drop_table('olympics_team_agg')
    # ### end Alembic commands ###
