"""add olympics rows

Revision ID: 5f3655b76586
Revises: cea0cea5b107
Create Date: 2026-02-10 21:40:53.270953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3655b76586'
down_revision = 'cea0cea5b107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
