"""add unique constraint manager+podr

Revision ID: 7385c3cbb0d7
Revises: 3dae9f7ac0cb
Create Date: 2026-01-24 15:36:28.856441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7385c3cbb0d7'
down_revision = '3dae9f7ac0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
