"""add teams

Revision ID: 7e142572d82e
Revises: 5e01bce9e70e
Create Date: 2026-02-17 10:16:04.474217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e142572d82e'
down_revision = '5e01bce9e70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_olympics_row_team', 'olympics_team_agg', ['team'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_olympics_row_team', 'olympics_team_agg', type_='unique')
    # ### end Alembic commands ###
