"""create olympics rows

Revision ID: 810ac1e8eb24
Revises: 5f3655b76586
Create Date: 2026-02-10 21:57:14.446262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810ac1e8eb24'
down_revision = '5f3655b76586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olympics_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('microgroup', sa.String(), nullable=False),
    sa.Column('dept', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('figure_skating_count', sa.Integer(), nullable=True),
    sa.Column('curling_count', sa.Integer(), nullable=True),
    sa.Column('snowboard_money', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_accounts', sa.Integer(), nullable=True),
    sa.Column('bills_paid', sa.Integer(), nullable=True),
    sa.Column('biathlon_count', sa.Integer(), nullable=True),
    sa.Column('freestyle_count', sa.Integer(), nullable=True),
    sa.Column('short_track_count', sa.Integer(), nullable=True),
    sa.Column('ski_alpenism_count', sa.Integer(), nullable=True),
    sa.Column('speed_skating_money', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('bobsleigh_money', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('northern_combination_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microgroup', 'dept', 'team', name='uq_olympics_row_microgroup')
    )
    op.create_index('ix_olympics_rows_dept', 'olympics_rows', ['dept'], unique=False)
    op.create_index('ix_olympics_rows_team', 'olympics_rows', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_olympics_rows_team', table_name='olympics_rows')
    op.drop_index('ix_olympics_rows_dept', table_name='olympics_rows')
    op.drop_table('olympics_rows')
    # ### end Alembic commands ###
