"""add olympics rows

Revision ID: cea0cea5b107
Revises: deb856e58984
Create Date: 2026-02-10 21:35:46.573402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea0cea5b107'
down_revision = 'deb856e58984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
