"""add unique constraint refractoring

Revision ID: deb856e58984
Revises: 7385c3cbb0d7
Create Date: 2026-01-26 06:37:29.045189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb856e58984'
down_revision = '7385c3cbb0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kts_manager_plan', 'plan',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('kts_manager_plan', 'procent',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.create_unique_constraint('uq_manager_podr', 'kts_manager_plan', ['manager', 'podr'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_manager_podr', 'kts_manager_plan', type_='unique')
    op.alter_column('kts_manager_plan', 'procent',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('kts_manager_plan', 'plan',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    # ### end Alembic commands ###
